openapi: 3.0.1
info:
  title: Progress-Account
  description: Process account specification to define the progress account API
  contact:
    email: scubatoy@gmail.com  
  version: 1.0
servers:
  - url: http://localhost:8080/v1
    description: Developer server
  - url: http://localhost/v1
    description: Production server
tags:
  - name: progresses
    description: Progress Acount    
paths:
  /progresses:
    get:
      summary: Retrieve all progresses.
      tags:
        - progresses
      security:
        - BearerAuth
      operationId: getAllProgresses
      responses:
        200:  
          $ref: '#/components/responses/SuccessGetAll'
        401:
          $ref: '#/components/responses/Unauthorized'
        500:
          $ref: '#/components/responses/ServerError'       
  /progress:
    post:
      summary: Create a new progress.
      tags:
        - progresses
      security:
        - BearerAuth
      operationId: createProgressAccount
      requestBody:
        $ref: '#/components/requestBody/progressBody'
      responses:
        201:  
          $ref: '#/components/responses/Created'
        400:
          $ref: '#/components/responses/BadRequest'          
        401:
          $ref: '#/components/responses/Unauthorized'
        500:
          $ref: '#/components/responses/ServerError'                
  /progress/{id}:
    get:
      summary: Get a progress by ID.
      tags:
        - progresses
      security:
        - BearerAuth
      operationId: getProgressByID
      parameters:
        - name: id
          in: path
          description: Progress ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:  
          $ref: '#/components/responses/Success'
        401:
          $ref: '#/components/responses/Unauthorized'          
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'               
    put:
      summary: Update a progress by ID.
      tags:
        - progresses
      security:
        - BearerAuth
      operationId: ProgressByID
      requestBody:
        $ref: '#/components/requestBody/progressBody'      
      parameters:
        - name: id
          in: path
          description: Progress ID
          required: true
          schema:
            type: integer
            format: int64            
      responses:
        202:  
          $ref: '#/components/responses/Accepted'
        400:
          $ref: '#/components/responses/BadRequest'               
        401:
          $ref: '#/components/responses/Unauthorized'          
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'       
    delete:
      summary: Delete a Progress by ID.
      tags:
        - progresses
      security:
        - BearerAuth
      operationId: deleteProgressByID
      parameters:
        - name: id
          in: path
          description: Progress ID
          required: true
          schema:
            type: integer
            format: int64            
      responses:
        204:  
          description: No connect
        401:
          $ref: '#/components/responses/Unauthorized'          
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'               
components:
  schemas:
    progress:
      required:
      - id
      - dateProgresses
      - headCircumference
      - height
      - weight
      - patient
      type: object    
      properties:
        id:
          type: integer
          format: int64
          example: 1      
        dateProgresses:
          type: string
          format: date
          example: 25/04/2020
        headCircumference:
          type: number
          format: double
          example: 0.74       
        height:
          type: number
          format: double
          example: 1.2          
        weight:
          type: number
          format: double
          example: 16.2   
        patient:
          $ref: '#/components/schemas/patient'   
    patient:
      required:
      - id
      - firstName
      - lastName
      - dateBirth
      - gender
      - phoneNumber
      type: object    
      properties:
        id:
          type: integer
          format: int64
          example: 1
        firstName:
          type: string
          minLength: 2
          example: 'Boonruang'
        lastName:
          type: string
          example: 'Seedapunt'
        dateBirth:
          type: string
          format: date
          example: 22/04/2020  
        gender:
          type: string
          example: M
          enum:
            - M 
            - F 
        phoneNumber:
          type: number 
          format: int32
          example: 555-555-555  
    requestBody:
      required:
      - dateProgresses
      - headCircumference
      - height
      - weight
      - patient
      type: object    
      properties:
        dateProgresses:
          type: string
          format: date
          example: 25/04/2020
        headCircumference:
          type: number
          format: double
          example: 0.74       
        height:
          type: number
          format: double
          example: 1.2          
        weight:
          type: number
          format: double
          example: 16.2   
        patient:
          $ref: '#/components/schemas/patient'
    body_response_error:
      required:
        - code_error
        - message
      type:
        object
      properties:
        code_error:
          type: integer
          format: int64
          example: 123
        message:
          type: string
          example: message_to_show_from_server
  requestBody:
    progressBody:
      description: Progress JSON object required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/requestBody'        
  responses:
    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/body_response_error'     
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/body_response_error'       
    ServerError:
      description: Server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/body_response_error'   
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/body_response_error'  
    Accepted:
      description: Accepted
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/progress'                
    Success:
      description: Ok
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/progress'             
    Created:
      description: Created
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/progress'                        
    SuccessGetAll:
      description: Ok
      content:
        application/json:
          schema:
             type: array
             items:
              oneOf:
                - $ref: '#/components/schemas/progress'  
                - $ref: '#/components/schemas/progress'  
  securitySchemes:
    BearerAuth:
      type: http
      scheme: Bearer
      bearerFormat: JWT
