openapi: 3.0.1
info:
  title: Report-Progress-Patient
  description: Report patient growth specification
  contact:
    email: scubatoy@gmail.com  
  version: 1.0
servers:
  - url: http://localhost:8080/v1
    description: Developer server
  - url: http://localhost/v1
    description: Production server
tags:
  - name: report-progress
    description: Get all progresses throught ID patient 
paths:
  /patient/{id}/progress:
    get:
      summary: Retrieve all progresses.
      tags:
        - report-progress
      security:
        - BearerAuth
      operationId: getAllProgressesThroughPatientById
      parameters:
        - name: id
          in: path
          description: Patient ID
          required: true
          schema:
            type: integer
            format: int64      
      responses:
        200:  
          $ref: '#/components/responses/Success'
        401:
          $ref: '#/components/responses/Unauthorized'          
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'           
components:
  schemas:
    progress:
      required:
      - id
      - dateProgresses
      - headCircumference
      - height
      - weight
      - patient
      type: object    
      properties:
        id:
          type: integer
          format: int64
          example: 1      
        dateProgresses:
          type: string
          format: date
          example: 25/04/2020
        headCircumference:
          type: number
          format: double
          example: 0.74       
        height:
          type: number
          format: double
          example: 1.2          
        weight:
          type: number
          format: double
          example: 16.2   
        patient:
          $ref: '#/components/schemas/patient'   
    patient:
      required:
      - id
      - firstName
      - lastName
      - dateBirth
      - gender
      - phoneNumber
      type: object    
      properties:
        id:
          type: integer
          format: int64
          example: 1
        firstName:
          type: string
          minLength: 2
          example: 'Boonruang'
        lastName:
          type: string
          example: 'Seedapunt'
        dateBirth:
          type: string
          format: date
          example: 22/04/2020  
        gender:
          type: string
          example: M
          enum:
            - M 
            - F 
        phoneNumber:
          type: number 
          format: int32
          example: 555-555-555  
    body_response_error:
      required:
        - code_error
        - message
      type:
        object
      properties:
        code_error:
          type: integer
          format: int64
          example: 123
        message:
          type: string
          example: message_to_show_from_server
  responses:
    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/body_response_error'     
    ServerError:
      description: Server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/body_response_error'   
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/body_response_error'  
    Success:
      description: Ok
      content:
        application/json:
          schema:
             type: array
             items:
              oneOf:
                - $ref: '#/components/schemas/progress'  
                - $ref: '#/components/schemas/progress'  
  securitySchemes:
    BearerAuth:
      type: http
      scheme: Bearer
      bearerFormat: JWT
